image: androidsdk/android-31
pipelines:
  branches:
    master:
      - step:
          name: Build Debug
          caches:
            - gradle
          image: bitbucketpipelines/android-ci-image
          script:
            - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
            - unzip -o -qq android-sdk.zip -d android-sdk

            - export ANDROID_HOME="/opt/atlassian/pipelines/agent/build/android-sdk"
            -  export PATH="$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH"
            - yes | sdkmanager "platform-tools"
            - yes | sdkmanager "platforms;android-31"
            - yes | sdkmanager "build-tools;30.0.3"
            - yes | sdkmanager "extras;android;m2repository"
            - yes | sdkmanager "extras;google;m2repository"
            - yes | sdkmanager "extras;google;instantapps"
            - yes | sdkmanager --licenses
            - ./gradlew assembleDebug

          artifacts:
            - app/build/outputs/**