package com.jobtick.android.network.model.response.draft

import com.jobtick.android.models.AttachmentModelV2

data class Data(
    val additional_fund: Any,
    val amount: Any,
    val assigned_at: Any,
    val attachments: List<AttachmentModelV2>,
    val bookmark_id: Any,
    val budget: String?,
    val budget_plan: Int?,
    val cancellation: Any,
    val cancelled_at: Any,
    val category_id: Int,
    val chat_closed: Boolean,
    val closed_at: Any,
    val completed_at: Any,
    val conversation: Any,
    val conversations: List<Any>,
    val created_at: String,
    val description: String,
    val due_date: Any,
    val due_time: DueTime,
    val flexible_time: Int,
    val hourly_rate: Any,
    val id: Int,
    val latitude: String,
    val location: String,
    val longitude: String,
    val musthave: List<String>,
    val offer_count: Int,
    val offer_sent: Boolean,
    val offers: List<Any>,
    val payment_type: String,
    val position: Position,
    val poster: Poster,
    val question_count: Int,
    val questions: List<Any>,
    val requirements: List<String>,
    val reschedule_requests: List<Any>,
    val review: List<Any>,
    val slug: String,
    val status: String,
    val task_type: String,
    val title: String,
    val total_hours: Any,
    val worker: Any
)