package com.jobtick.android.models.response

data class Data(
    val about: String?,
    val account_status: AccountStatus?,
    val avatar: Avatar?,
    val badges: List<Badge>?,
    val blocked: Boolean?,
    val blocked_until: Any?,
    val browsejobs_default_filters: BrowsejobsDefaultFilters?,
    val business_number: Any?,
    val dob: String?,
    val email: String?,
    val email_verified_at: String?,
    val fname: String?,
    val id: Int?,
    val is_online: Boolean?,
    val is_verified_account: Int?,
    val join_date: String?,
    val last_online: String?,
    val lname: String?,
    val location: String?,
    val mobile: String?,
    val mobile_verified_at: String?,
    val name: String?,
    val portfolio: List<Any>?,
    val position: Position?,
    val posted_task_statistics: PostedTaskStatistics?,
    val poster_rank: Int?,
    val poster_ratings: Any?,
    val poster_tier: PosterTier?,
    val skills: Skills?,
    val tagline: String?,
    val work_task_statistics: WorkTaskStatistics?,
    val worker_rank: Int?,
    val worker_ratings: Any?,
    val worker_tier: WorkerTier?
)